# Numpy 101

Bu challenge’ın amacı Numpy kütüphanesine alışmak, multidimensional array’leri manipüle etmek ve `for` loops kullanmadan bazı linear algebra işlemlerini uygulamaktır. 

💡 Bu challenge boyunca  [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) dosyasını kapalı tutmayı unutma.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Boyutu 10 olan ve yalnızca sıfırlardan (`0`) oluşan bir null vector oluştur ve `ten_zeros` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [32]:
ten_zeros=np.zeros(10)

---

**Q2** - 5’ten 10’a kadar olan değerleri içeren bir vector oluştur ve `five_to_ten` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [34]:
five_to_ten=np.arange(5,11)

---

**Q3** - Aşağıdaki matrisi bir NumPy `ndarray` olarak oluştur ve `A` adlı bir değişkene ata:
$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [9]:
A=np.array([(5,9,7),(1,0,3)])

In [10]:
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Aşağıdaki matrisi `np.array()`  constructor’ını kullanmadan oluştur ve `B` adlı bir değişkene ata:
$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [11]:
B=[(1,1),(1,1)]


---

**Q5** - `-1` ile `1` arasında eşit aralıklarla bölünmüş 20 elemanlı bir vector oluştur ve `lin_twenty` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [36]:
lin_twenty=np.linspace(-1,1,20)

---

**Q6** - 3x3 boyutunda bir identity matrix oluştur ve `C` adlı bir değişkene ata:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [38]:
C=np.eye(3)

---

**Q7** - Aşağıdaki `ndarray` ’i oluştur ve `D` adlı bir değişkene ata:  


$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

-`D` değişkenini 2x3’lük bir matrise reshape et ve `E` adlı bir değişkene ata:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [41]:
D=np.array([2,9,7,3,1,5])
E=D.reshape(2,3)

---

**Q8**: Bu `ndarray` olan `F` ’in ikinci sütununu seç, 4 satır ve 1 sütundan oluşan bir `ndarray` olacak şekilde reshape et ve `reshaped_F` adlı bir değişkene ata:

$
reshaped\_F = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [23]:
F = np.random.random((4, 5))
print(F)

[[0.57857396 0.97195551 0.51725214 0.29045042 0.01104505]
 [0.57430887 0.96553576 0.90948786 0.90303233 0.20069042]
 [0.58812067 0.14263711 0.39392548 0.69227849 0.26997695]
 [0.6295585  0.67589143 0.12502769 0.81316162 0.21980857]]


In [26]:
F[:,1]
reshaped_F=F[:,1].reshape(4,1)

In [27]:
reshaped_F

array([[0.97195551],
       [0.96553576],
       [0.14263711],
       [0.67589143]])

---

**Q9** - Matrisler`G` ve `H` ’nin toplamını hesapla ve sonucu `gh_sum` adlı bir değişkende sakla:
$
G = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
H =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
G + H = ?
$


In [28]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
G = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('G: \n', G)
H = np.array([[0, 1], [1, -1], [2, 3]])
print('H: \n', H)

G: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
H: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [30]:
gh_sum=G+H
gh_sum

array([[ 0,  5],
       [-3, -4],
       [ 3,  4]])

## Kodunu Kontrol Et!

Kodunu kontrol etmek için aşağıdaki cell’i çalıştır:

In [42]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_F=reshaped_F,
    gh_sum=gh_sum
)
result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/scorp08/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/scorp08/workintech_projeler/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 5 items

test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED     [ 20%]
test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED      [ 40%]
test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping PASSED    [ 60%]
test_numpy.py::TestNumpy::test_ndarrays_creation FAILED                  [ 80%]
test_numpy.py::TestNumpy::test_vectors_creation PASSED                   [100%]

=================================== FAILURES ===================================
_______________________ TestNumpy.test_ndarrays_creation _______________________

self = <test_numpy.TestNumpy testMethod=test_ndarrays_creation>

    def test_ndar